/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Label;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Patient;

/**
 *
 * @author admin
 */
public class FormPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    private JPanel BottomPanel;
    public FormPanel(JPanel Bottompanel) {
        initComponents();
        this.BottomPanel = Bottompanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        titleForm = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        lastnameLabel1 = new javax.swing.JLabel();
        lastnameTextField1 = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        photoLabel = new javax.swing.JLabel();
        photobutton = new javax.swing.JButton();
        genderLabel = new javax.swing.JLabel();
        patientComboBox = new javax.swing.JComboBox<>();
        patientLabel1 = new javax.swing.JLabel();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        noneButton = new javax.swing.JRadioButton();
        messageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();

        MainPanel.setBackground(new java.awt.Color(255, 255, 153));

        titleForm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleForm.setText("Patient Registration Form");
        titleForm.setToolTipText("");

        firstnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstnameLabel.setText("First name: ");

        ageLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ageLabel.setText("Age: ");

        firstnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTextFieldActionPerformed(evt);
            }
        });

        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });

        lastnameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lastnameLabel1.setText("Last name: ");

        lastnameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTextField1ActionPerformed(evt);
            }
        });

        submitbutton.setBackground(new java.awt.Color(255, 153, 102));
        submitbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLabel.setText("Email:");

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        photoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        photoLabel.setText("Choose photo:");

        photobutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        photobutton.setText("Choose file");
        photobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photobuttonActionPerformed(evt);
            }
        });
        photobutton.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                photobuttonPropertyChange(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderLabel.setText("Gender:");

        patientComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Special" }));
        patientComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientComboBoxActionPerformed(evt);
            }
        });

        patientLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientLabel1.setText("Patient Type:");

        genderGroup.add(maleButton);
        maleButton.setText("Male");
        maleButton.setActionCommand("MALE\n\n");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });

        genderGroup.add(femaleButton);
        femaleButton.setText("Female");
        femaleButton.setActionCommand("FEMALE\n");

        genderGroup.add(noneButton);
        noneButton.setText("Other");
        noneButton.setActionCommand("OTHERS\n");

        messageLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        messageLabel.setText("Message:");

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        messageTextArea.setDragEnabled(true);
        jScrollPane1.setViewportView(messageTextArea);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderLabel)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(patientLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(firstnameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lastnameLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(photoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(messageLabel))
                        .addGap(131, 200, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(photobutton)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(firstnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                .addComponent(ageTextField)
                                .addComponent(lastnameTextField1)
                                .addComponent(emailTextField)
                                .addComponent(patientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(femaleButton)
                                    .addComponent(maleButton)
                                    .addComponent(noneButton)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleForm)
                .addGap(225, 225, 225))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleForm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientLabel1)
                    .addComponent(patientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(maleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femaleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noneButton)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(messageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoLabel)
                    .addComponent(photobutton))
                .addGap(23, 23, 23)
                .addComponent(submitbutton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_firstnameTextFieldActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void lastnameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTextField1ActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
        Patient newpat = new Patient();
        String first = firstnameTextField.getText();
        String last = lastnameTextField1.getText();
        String age = ageTextField.getText();
        String email= emailTextField.getText();
        String gender = genderGroup.getSelection().getActionCommand();
        String type = patientComboBox.getSelectedItem().toString();
        String message = messageTextArea.getText();
        
        
        newpat.setFirst(first);
        newpat.setLast(last);
        newpat.setAge(age);
        newpat.setEmail(email);
        newpat.setGender(gender);
        newpat.setMessage(message);
        newpat.setType(type);
//        System.out.println(gender);

        if(first.matches("^[a-zA-Z]*$")){
            if(last.matches("^[a-zA-Z]*$")){
                    if(age.matches("[1-9]+")){
                        if(email.matches("^[A-Za-z0-9.%-]+@[A-Za-z0-9.]+$")){
                            if(genderGroup.isSelected((ButtonModel) noneButton.getModel()) != true && genderGroup.isSelected((ButtonModel) maleButton.getModel()) != true && true!=genderGroup.isSelected((ButtonModel) femaleButton.getModel())){
                                JOptionPane
                                        .showMessageDialog(this, "Select Gender");
                                
                            }
                            else{
                                ViewPanel newviewpanel = new ViewPanel(newpat);
                                BottomPanel.add(newviewpanel);
                                CardLayout layout = (CardLayout) BottomPanel.getLayout();
                                layout.next(BottomPanel);
                                
                                
                            }
                            
//                                if((maleButton.isSelected()==false)&&(femaleButton.isSelected()==false)&&(noneButton.isSelected()==false)){
//                                    JOptionPane
//                                    .showMessageDialog(this, "Select Gender");
//                                }
//                            
//                            else{
//                                ViewPanel newviewpanel = new ViewPanel(newpat);
//                                 BottomPanel.add(newviewpanel);
//                                 CardLayout layout = (CardLayout) BottomPanel.getLayout();
//                                 layout.next(BottomPanel);
//                            
//                            }
//                           
                            
                            
                            
                            
                            
                            

                }
                else{
                    JOptionPane
                    .showMessageDialog(this, "Enter Valid email");
                }

                }
                else{
                    JOptionPane
                    .showMessageDialog(this, "Enter Valid age");
                }
            }
            else{
                JOptionPane
                .showMessageDialog(this, "Enter Valid last name");
            }
        }
        else{
           JOptionPane
            .showMessageDialog(this, "Enter Valid first name");
        }
        
        
        

        
        //.showMessageDialog(this, "User: "+ first +" "+ last +", " +"age is "+ age+ " "+"and email is "+ email, "User Information", HEIGHT, setIconImage(icon));
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void photobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photobuttonActionPerformed
        // TODO add your handling code here:
        //imagechoose();
        //        JFileChooser j = new JFileChooser();
        //        FileNameExtensionFilter filter = new FileNameExtensionFilter("Only Images", "jpg","jpeg","png","gif");
        //        j.setFileFilter(filter);
        //        j.showOpenDialog(this);
        //        String file = j.getSelectedFile().getName();
        imagechoose();
        //        System.out.println(file);

    }//GEN-LAST:event_photobuttonActionPerformed
public void imagechoose(){
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Only Images", "jpg","jpeg","png","gif");
        j.setFileFilter(filter);
        j.showOpenDialog(this);
        
        String file =j.getSelectedFile().getName(); 
        photobutton.setText(file);
        
        
        
    }
    private void photobuttonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_photobuttonPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_photobuttonPropertyChange

    private void patientComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientComboBoxActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel MainPanel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastnameLabel1;
    private javax.swing.JTextField lastnameTextField1;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JRadioButton noneButton;
    private javax.swing.JComboBox<String> patientComboBox;
    private javax.swing.JLabel patientLabel1;
    private javax.swing.JLabel photoLabel;
    public javax.swing.JButton photobutton;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel titleForm;
    // End of variables declaration//GEN-END:variables

    
}
