/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Patient;

/**
 *
 * @author admin
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    private Patient newpat;
    public ViewPanel(Patient newpat) {
        initComponents();
        this.newpat = newpat;
        populatedata();
                
    }

    ViewPanel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noneButton1 = new javax.swing.JPanel();
        titleForm = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        firstnameTextFieldView = new javax.swing.JTextField();
        ageTextFieldView = new javax.swing.JTextField();
        lastnameLabel1 = new javax.swing.JLabel();
        lastnameTextFieldView = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextFieldView = new javax.swing.JTextField();
        genderLabel1 = new javax.swing.JLabel();
        patientLabel2 = new javax.swing.JLabel();
        messageLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageTextAreaView = new javax.swing.JTextArea();
        typeViewPanelView = new javax.swing.JTextField();
        genderTextViewpanel = new javax.swing.JTextField();

        noneButton1.setBackground(new java.awt.Color(255, 255, 153));

        titleForm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleForm.setText("Patient Details");
        titleForm.setToolTipText("");

        firstnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstnameLabel.setText("First name: ");

        ageLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ageLabel.setText("Age: ");

        firstnameTextFieldView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTextFieldViewActionPerformed(evt);
            }
        });

        ageTextFieldView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldViewActionPerformed(evt);
            }
        });

        lastnameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lastnameLabel1.setText("Last name: ");

        lastnameTextFieldView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTextFieldViewActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLabel.setText("Email:");

        emailTextFieldView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldViewActionPerformed(evt);
            }
        });

        genderLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        genderLabel1.setText("Gender:");

        patientLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientLabel2.setText("Patient Type:");

        messageLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        messageLabel1.setText("Message:");

        messageTextAreaView.setColumns(20);
        messageTextAreaView.setRows(5);
        messageTextAreaView.setDragEnabled(true);
        jScrollPane2.setViewportView(messageTextAreaView);

        genderTextViewpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTextViewpanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout noneButton1Layout = new javax.swing.GroupLayout(noneButton1);
        noneButton1.setLayout(noneButton1Layout);
        noneButton1Layout.setHorizontalGroup(
            noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noneButton1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genderLabel1)
                    .addGroup(noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(patientLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addComponent(firstnameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lastnameLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(messageLabel1))
                .addGroup(noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noneButton1Layout.createSequentialGroup()
                        .addGap(15, 15, Short.MAX_VALUE)
                        .addGroup(noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstnameTextFieldView, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(ageTextFieldView)
                            .addComponent(lastnameTextFieldView)
                            .addComponent(emailTextFieldView)))
                    .addGroup(noneButton1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeViewPanelView)
                            .addComponent(genderTextViewpanel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))))
                .addGap(193, 193, 193))
            .addGroup(noneButton1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(titleForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        noneButton1Layout.setVerticalGroup(
            noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noneButton1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleForm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameTextFieldView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameTextFieldView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTextFieldView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailLabel)
                    .addComponent(emailTextFieldView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientLabel2)
                    .addComponent(typeViewPanelView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel1)
                    .addComponent(genderTextViewpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(noneButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageLabel1))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(noneButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noneButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameTextFieldViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTextFieldViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTextFieldViewActionPerformed

    private void ageTextFieldViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldViewActionPerformed

    private void lastnameTextFieldViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTextFieldViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTextFieldViewActionPerformed

    private void emailTextFieldViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldViewActionPerformed

    private void genderTextViewpanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTextViewpanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTextViewpanelActionPerformed
public String imagechoose(){
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Only Images", "jpg","jpeg","png","gif");
        j.setFileFilter(filter);
        j.showOpenDialog(this);
        String file =j.getSelectedFile().getName(); 
        
        return file;
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextFieldView;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextFieldView;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameTextFieldView;
    private javax.swing.JLabel genderLabel1;
    private javax.swing.JTextField genderTextViewpanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastnameLabel1;
    private javax.swing.JTextField lastnameTextFieldView;
    private javax.swing.JLabel messageLabel1;
    private javax.swing.JTextArea messageTextAreaView;
    public javax.swing.JPanel noneButton1;
    private javax.swing.JLabel patientLabel2;
    private javax.swing.JLabel titleForm;
    private javax.swing.JTextField typeViewPanelView;
    // End of variables declaration//GEN-END:variables

    private void populatedata() {
        firstnameTextFieldView.setText(this.newpat.getFirst());
        lastnameTextFieldView.setText(this.newpat.getLast());
        ageTextFieldView.setText(this.newpat.getAge());
        emailTextFieldView.setText(this.newpat.getEmail());
        typeViewPanelView.setText(this.newpat.getType());
        genderTextViewpanel.setText(this.newpat.getGender());
        messageTextAreaView.setText(this.newpat.getMessage());
    }
    
}
