/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import com.sun.source.tree.BreakTree;
import com.sun.source.tree.ContinueTree;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author admin
 */
public class MainFrame extends NewClass {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        titleForm = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        lastnameLabel1 = new javax.swing.JLabel();
        lastnameTextField1 = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        photoLabel = new javax.swing.JLabel();
        photobutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(255, 255, 153));

        titleForm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleForm.setText("USER FORM");
        titleForm.setToolTipText("");

        firstnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstnameLabel.setText("First name: ");

        ageLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ageLabel.setText("Age: ");

        firstnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTextFieldActionPerformed(evt);
            }
        });

        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });

        lastnameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lastnameLabel1.setText("Last name: ");

        lastnameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTextField1ActionPerformed(evt);
            }
        });

        submitbutton.setBackground(new java.awt.Color(255, 153, 102));
        submitbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLabel.setText("Email:");

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        photoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        photoLabel.setText("Choose photo:");

        photobutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        photobutton.setText("Choose file");
        photobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photobuttonActionPerformed(evt);
            }
        });
        photobutton.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                photobuttonPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(titleForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(0, 213, Short.MAX_VALUE)
                .addComponent(submitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastnameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(photoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(131, 131, 131)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstnameTextField)
                    .addComponent(ageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(lastnameTextField1)
                    .addComponent(emailTextField)
                    .addComponent(photobutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleForm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoLabel)
                    .addComponent(photobutton))
                .addGap(43, 43, 43)
                .addComponent(submitbutton)
                .addGap(65, 65, 65))
        );

        submitbutton.getAccessibleContext().setAccessibleDescription("");
        submitbutton.getAccessibleContext().setAccessibleParent(photobutton);
        photobutton.getAccessibleContext().setAccessibleParent(photobutton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_firstnameTextFieldActionPerformed

    private void lastnameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTextField1ActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
        String first = firstnameTextField.getText();
        String last = lastnameTextField1.getText();
        String age = ageTextField.getText();
        String email= emailTextField.getText();
        
        if(first.matches("^[a-zA-Z]*$")){
            
        }
        else{
            JOptionPane
                    .showMessageDialog(this, "Enter Valid first name");
        }
        if(last.matches("^[a-zA-Z]*$")){
            
        }
        else{
            JOptionPane
                    .showMessageDialog(this, "Enter Valid last name");
        }
        if(age.matches("[1-9]+")){
            
        }
        else{
            JOptionPane
                    .showMessageDialog(this, "Enter Valid age");
        }
        if(email.matches("^[A-Za-z0-9.%-]+@[A-Za-z0-9.]+$")){
            
        }
        else{
            JOptionPane
                    .showMessageDialog(this, "Enter Valid email");
        }
        
        
        JOptionPane
                .showMessageDialog(this, "User: "+ first +" "+ last +", " +"age is "+ age+ " "+"and email is "+ email, "User Information", HEIGHT);
                //.showMessageDialog(this, "User: "+ first +" "+ last +", " +"age is "+ age+ " "+"and email is "+ email, "User Information", HEIGHT, setIconImage(icon));
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void photobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photobuttonActionPerformed
        // TODO add your handling code here:
        //imagechoose();
//        JFileChooser j = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Only Images", "jpg","jpeg","png","gif");
//        j.setFileFilter(filter);
//        j.showOpenDialog(this);
//        String file = j.getSelectedFile().getName();
          String file = imagechoose();
          photobutton.setText(file);
//        System.out.println(file);
        
        
    }//GEN-LAST:event_photobuttonActionPerformed

    public String imagechoose(){
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Only Images", "jpg","jpeg","png","gif");
        j.setFileFilter(filter);
        j.showOpenDialog(this);
        String file =j.getSelectedFile().getName(); 
        
        return file;
        
        
    }
    private void photobuttonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_photobuttonPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_photobuttonPropertyChange

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed
    // TODO add your handling code here:


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel MainPanel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel lastnameLabel1;
    private javax.swing.JTextField lastnameTextField1;
    private javax.swing.JLabel photoLabel;
    public javax.swing.JButton photobutton;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel titleForm;
    // End of variables declaration//GEN-END:variables
}
